"use client";
import { useRouter } from "next/navigation";
import Script from "next/script";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { CountrySelect } from "@/components/commerce/country-select";
declare global { interface Window { Square?: { payments: (app: string, location: string) => { card: () => Promise<Card> } } } }
type TokenizationError = { code?: string; detail?: string; message?: string };
type TokenizationResult = { status: string; token?: string; errors?: TokenizationError[] };
type Card = { attach: (target: HTMLElement) => Promise<void>; destroy?: () => Promise<void> | void; tokenize: (details: unknown) => Promise<TokenizationResult> };
type Format = "PAPERBACK" | "HARDCOVER";
type Fields = Record<"firstName" | "lastName" | "email" | "phone" | "address1" | "address2" | "city" | "state" | "postalCode" | "country", string>;
const initial: Fields = { firstName: "", lastName: "", email: "", phone: "", address1: "", address2: "", city: "", state: "", postalCode: "", country: "US" };
const fields = (Object.keys(initial) as (keyof Fields)[]).filter((key) => key !== "country");
export function CheckoutForm({ initialFormat = "PAPERBACK" }: { initialFormat?: Format }) {
  const router = useRouter(); const [values, setValues] = useState(initial); const [format, setFormat] = useState<Format>(initialFormat); const [quantity, setQuantity] = useState(1); const [methods, setMethods] = useState<{ id: string; label: string }[]>([]); const [method, setMethod] = useState(""); const [total, setTotal] = useState<number | null>(null); const [loading, setLoading] = useState(false); const [sdkLoaded, setSdkLoaded] = useState(false); const [cardReady, setCardReady] = useState(false); const [cardContainer, setCardContainer] = useState<HTMLDivElement | null>(null); const [error, setError] = useState("");
  const card = useRef<Card | null>(null); const paymentKey = useRef(crypto.randomUUID()); const retry = useRef<{ orderNumber: string; token: string } | null>(null); const appId = process.env.NEXT_PUBLIC_SQUARE_APPLICATION_ID; const locationId = process.env.NEXT_PUBLIC_SQUARE_LOCATION_ID; const payload = useMemo(() => ({ ...values, format, quantity }), [values, format, quantity]); const cardContainerRef = useCallback((node: HTMLDivElement | null) => { if (!node) { const instance = card.current; card.current = null; setCardReady(false); if (instance?.destroy) void Promise.resolve(instance.destroy()).catch(() => undefined); } setCardContainer(node); }, []);
  useEffect(() => { if (!sdkLoaded || !appId || !locationId || !window.Square || !cardContainer || card.current) return; const payments = window.Square.payments(appId, locationId); let cancelled = false; void (async () => { let instance: Card | null = null; try { instance = await payments.card(); if (cancelled || !cardContainer.isConnected) { await instance.destroy?.(); return; } await instance.attach(cardContainer); if (cancelled || !cardContainer.isConnected) { await instance.destroy?.(); return; } card.current = instance; setCardReady(true); } catch { if (!cancelled) setError("Secure card payment could not be loaded."); } })(); return () => { cancelled = true; }; }, [sdkLoaded, appId, locationId, cardContainer]);
  const reset = () => { setMethods([]); setMethod(""); setTotal(null); };
  const set = (key: keyof Fields, value: string) => { setValues((current) => ({ ...current, [key]: value })); reset(); };
  async function quote() { setLoading(true); setError(""); try { const response = await fetch("/api/commerce/quote", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!data.ok) return setError(data.error); const options = Array.isArray(data.shippingOptions) ? data.shippingOptions : Object.values(data.shippingOptions ?? {}).find(Array.isArray) ?? []; setMethods((options as Record<string, unknown>[]).map((option) => ({ id: String(option.level ?? option.id ?? option.shipping_level ?? option.code ?? ""), label: String(option.name ?? option.description ?? option.level ?? "Shipping") })).filter((option) => option.id)); } catch { setError("Shipping service is unavailable."); } finally { setLoading(false); } }
  async function choose(shippingMethod: string) { setMethod(shippingMethod); setLoading(true); try { const response = await fetch("/api/commerce/quote", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...payload, shippingMethod }) }); const data = await response.json(); if (!data.ok) return setError(data.error); setTotal(data.totalAmount); } catch { setError("Shipping quote confirmation failed."); } finally { setLoading(false); } }
  async function buy() { const instance = card.current; if (!instance || total === null || !method) return setError("Select shipping and wait for the secure card form."); setLoading(true); setError(""); try { const result = await instance.tokenize({ amount: (total / 100).toFixed(2), currencyCode: "USD", intent: "CHARGE", customerInitiated: true, sellerKeyedIn: false, billingContact: { givenName: values.firstName, familyName: values.lastName, email: values.email, phone: values.phone, addressLines: [values.address1, ...(values.address2 ? [values.address2] : [])], city: values.city, state: values.state, postalCode: values.postalCode, countryCode: values.country } }); if (result.status !== "OK" || !result.token) { const firstError = result.errors?.[0]; const detail = [firstError?.code, firstError?.detail ?? firstError?.message].filter(Boolean).join(": ").slice(0, 240); console.warn("Square card tokenization failed.", { status: result.status, code: firstError?.code, detail: firstError?.detail ?? firstError?.message }); return setError(detail ? `Card tokenization failed: ${detail}` : "Card tokenization failed."); } const response = await fetch("/api/commerce/charge", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...payload, shippingMethod: method, paymentToken: result.token, idempotencyKey: paymentKey.current, ...(retry.current ? { retryOrderNumber: retry.current.orderNumber, orderAccessToken: retry.current.token } : {}) }) }); const data = await response.json(); if (!data.ok) { if (data.retryOrderNumber && data.orderAccessToken) { retry.current = { orderNumber: data.retryOrderNumber, token: data.orderAccessToken }; paymentKey.current = crypto.randomUUID(); } return setError(data.error ?? "Payment could not be processed."); } router.push(`/order/${data.orderNumber}/access?token=${encodeURIComponent(data.orderAccessToken)}`); } catch { setError("Payment could not be processed."); } finally { setLoading(false); } }
  return <><Script src={process.env.NEXT_PUBLIC_SQUARE_ENVIRONMENT === "production" ? "https://web.squarecdn.com/v1/square.js" : "https://sandbox.web.squarecdn.com/v1/square.js"} strategy="afterInteractive" onLoad={() => setSdkLoaded(true)} /><section className="bg-ivory"><div className="mx-auto max-w-3xl px-5 py-16"><p className="text-xs font-semibold uppercase tracking-[.22em] text-gold-deep">Direct purchase</p><h1 className="mt-4 font-serif text-4xl text-ink">Buy the book</h1><div className="mt-10 rounded-md border border-hairline bg-paper p-6"><div className="grid gap-4 sm:grid-cols-2">{fields.map((key) => <label key={key} className={key.includes("address") ? "sm:col-span-2" : ""}><span className="text-xs uppercase text-ink/60">{key.replace(/([A-Z])/g, " $1")}</span><input value={values[key]} onChange={(event) => set(key, event.target.value)} className="mt-1 w-full border border-hairline bg-white px-3 py-2" /></label>)}<CountrySelect value={values.country} onChange={(country) => set("country", country)} /></div><div className="mt-6 flex gap-3">{(["PAPERBACK", "HARDCOVER"] as const).map((value) => <button type="button" key={value} onClick={() => { setFormat(value); reset(); }} className={`border px-4 py-2 ${format === value ? "border-gold" : "border-hairline"}`}>{value === "PAPERBACK" ? "Paperback" : "Hardcover"}</button>)}</div><input aria-label="Quantity" type="number" min="1" max="10" value={quantity} onChange={(event) => { setQuantity(Math.max(1, Math.min(10, Number(event.target.value) || 1))); reset(); }} className="mt-4 w-24 border border-hairline px-3 py-2" /><button type="button" onClick={quote} disabled={loading} className="ml-4 bg-ink px-5 py-3 text-ivory">Get shipping options</button>{methods.map((option) => <label key={option.id} className="mt-4 block"><input type="radio" checked={method === option.id} onChange={() => choose(option.id)} /> <span className="ml-2">{option.label}</span></label>)}{total !== null ? <div className="mt-6"><p className="font-serif text-2xl">Total: ${(total / 100).toFixed(2)}</p><div ref={cardContainerRef} className="mt-4 border border-hairline bg-white p-4" /><button type="button" onClick={buy} disabled={loading || !cardReady} className="mt-4 bg-gold px-5 py-3">{loading ? "Processing…" : "Buy the book"}</button></div> : null}{error ? <p role="alert" className="mt-4 text-destructive">{error}</p> : null}</div></div></section></>;
}
