ALTER TYPE "BookFormat" ADD VALUE IF NOT EXISTS 'EBOOK';

ALTER TABLE "Order"
  ALTER COLUMN "addressLine1" DROP NOT NULL,
  ALTER COLUMN "city" DROP NOT NULL,
  ALTER COLUMN "stateProvince" DROP NOT NULL,
  ALTER COLUMN "postalCode" DROP NOT NULL,
  ALTER COLUMN "country" DROP NOT NULL;
